name: shopping_cart
description: ShoppingCart is a Flutter library that simplifies the creation and management of a shopping cart in your Flutter applications.
version: 0.0.2
homepage:
repository: https://github.com/egortabula/shopping_cart
issue_tracker: https://github.com/egortabula/shopping_cart/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'This screenshot shows the thumbnail of the package'
    path: lib/shopping_cart_flutter_package.jpg

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
